# Generated by Django 4.2.13 on 2024-06-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("external_services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_column="oauth_token", max_length=255)),
                (
                    "refresh_token",
                    models.CharField(db_column="refresh_token", max_length=255),
                ),
                ("token_uri", models.CharField(db_column="token_uri", max_length=255)),
                ("client_id", models.CharField(db_column="client_id", max_length=255)),
                (
                    "client_secret",
                    models.CharField(db_column="client_secret", max_length=255),
                ),
                ("scopes", models.CharField(db_column="scopes", max_length=255)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "CALENDAR",
            },
        ),
    ]
