# Generated by Django 4.2.13 on 2024-06-20 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("external_services", "0002_calendar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_news",
            name="news_id",
        ),
        migrations.RemoveField(
            model_name="user_news",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="calendar",
            name="user_id",
        ),
        migrations.AddField(
            model_name="calendar",
            name="expires_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="calendar",
            name="user",
            field=models.OneToOneField(
                db_column="user_id",
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="News",
        ),
        migrations.DeleteModel(
            name="User_News",
        ),
    ]
