# Generated by Django 4.2.13 on 2024-06-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productivitymode",
            name="selected_day",
            field=models.CharField(db_column="selected_day"),
        ),
    ]
