# Generated by Django 4.2.13 on 2024-06-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firebase_token",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
