# Generated by Django 4.2.13 on 2024-06-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_firebase_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="firebase_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
