# Generated by Django 4.2.13 on 2024-06-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_firebase_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
    ]
