# Generated by Django 4.2.13 on 2024-06-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_user_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="firebase_token",
        ),
    ]
